# Generated by Django 4.0.2 on 2022-03-16 14:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_remove_collection_list_nfts'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='name',
            field=models.CharField(default='Apokl', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='nfts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
