# Generated by Django 4.0.2 on 2022-03-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0003_collection_name_collection_nfts'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
