# Generated by Django 4.0.2 on 2022-03-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0004_collection_description_alter_collection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.CharField(default='Atest', max_length=200, unique=True),
        ),
    ]
