# Generated by Django 4.0.2 on 2022-03-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0005_collection_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='slug',
        ),
    ]
