# Generated by Django 4.0.2 on 2022-03-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0007_collection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
