# Generated by Django 4.0.2 on 2022-04-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0010_collection_picture_alter_creator_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
