# Generated by Django 4.0.2 on 2022-04-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0012_alter_collection_picture_alter_creator_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='picture',
            field=models.ImageField(default='', max_length=1000, upload_to='photos/collection/<django.db.models.fields.CharField>_<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='picture',
            field=models.ImageField(default='', max_length=1000, upload_to='photos/creator/<django.db.models.fields.CharField>'),
        ),
    ]
