# Generated by Django 4.0.2 on 2022-04-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0013_alter_collection_picture_alter_creator_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='discordUrl',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='creator',
            name='instagramUrl',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='creator',
            name='twitterUrl',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='creator',
            name='youtubeUrl',
            field=models.CharField(default='', max_length=500),
        ),
    ]
