# Generated by Django 4.0.2 on 2022-04-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0014_creator_discordurl_creator_instagramurl_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ['-id']},
        ),
    ]
