# Generated by Django 4.0.2 on 2022-04-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0016_alter_collection_creator_alter_collection_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='creator',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.CharField(default='Atest', max_length=200, unique=True),
        ),
    ]
