# Generated by Django 4.0.2 on 2022-04-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0017_alter_collection_creator_alter_collection_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
