# Generated by Django 4.0.2 on 2022-04-29 17:47

import creators.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0018_creator_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='picture',
            field=models.ImageField(default='', max_length=1000, upload_to=creators.models.collection_directory_path),
        ),
        migrations.AlterField(
            model_name='creator',
            name='discordUrl',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='creator',
            name='instagramUrl',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='creator',
            name='picture',
            field=models.ImageField(default='', max_length=1000, upload_to=creators.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='creator',
            name='twitterUrl',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='creator',
            name='youtubeUrl',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
