# Generated by Django 4.0.2 on 2022-04-29 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creators', '0019_alter_collection_picture_alter_creator_discordurl_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={},
        ),
        migrations.AddField(
            model_name='creator',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creator',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
