# Generated by Django 4.0.2 on 2022-04-30 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0020_alter_creator_options_creator_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='nfts',
            new_name='nfts_array',
        ),
        migrations.AlterField(
            model_name='collection',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='creators.creator'),
        ),
    ]
