# Generated by Django 4.0.2 on 2022-04-30 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0021_rename_nfts_collection_nfts_array_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='creators.creator'),
        ),
    ]
