# Generated by Django 4.0.2 on 2022-05-06 09:42

import creators.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0023_alter_creator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='picture',
            field=models.ImageField(blank=True, default='', max_length=1000, upload_to=creators.models.collection_directory_path),
        ),
    ]
