# Generated by Django 4.0.2 on 2022-06-22 13:36

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=500)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('description', models.TextField(blank=True)),
                ('picture', models.ImageField(default='', max_length=1000, upload_to=profiles.models.user_directory_path)),
                ('instagramUrl', models.CharField(blank=True, default='', max_length=500)),
                ('twitterUrl', models.CharField(blank=True, default='', max_length=500)),
                ('youtubeUrl', models.CharField(blank=True, default='', max_length=500)),
                ('discordUrl', models.CharField(blank=True, default='', max_length=500)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
