# Generated by Django 4.0.2 on 2022-04-16 12:06

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0014_creator_discordurl_creator_instagramurl_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='stars',
        ),
        migrations.AddField(
            model_name='room',
            name='adresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='room',
            name='picture',
            field=models.ImageField(default='', max_length=1000, upload_to='photos/rooms/<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.AddField(
            model_name='room',
            name='picture2',
            field=models.ImageField(default='', max_length=1000, upload_to='photos/rooms/<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.AddField(
            model_name='room',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10000), blank=True, default=list, size=None),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('picture', models.ImageField(default='', max_length=1000, upload_to='photos/rooms/posts/<django.db.models.fields.related.ForeignKey>')),
                ('picture2', models.ImageField(default='', max_length=1000, upload_to='photos/rooms/posts/<django.db.models.fields.related.ForeignKey>')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creators.collection')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
