# Generated by Django 4.0.2 on 2022-04-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_post_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='', max_length=1000, upload_to='photos/rooms/posts/<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture2',
            field=models.ImageField(blank=True, default='', max_length=1000, upload_to='photos/rooms/posts/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
