# Generated by Django 4.0.2 on 2022-04-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0015_alter_collection_options_alter_creator_options'),
        ('rooms', '0004_alter_post_picture_alter_post_picture2'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Room', to='creators.collection'),
        ),
        migrations.AlterField(
            model_name='post',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='creators.collection'),
        ),
    ]
