# Generated by Django 4.0.2 on 2022-04-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_collection_alter_post_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='adresses',
            new_name='addresses',
        ),
    ]
