# Generated by Django 4.0.2 on 2022-04-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_rename_adresses_room_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='', max_length=2000, upload_to='photos/rooms/posts/<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture2',
            field=models.ImageField(blank=True, default='', max_length=2000, upload_to='photos/rooms/posts/<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.AlterField(
            model_name='room',
            name='picture',
            field=models.ImageField(blank=True, default='', max_length=2000, upload_to='photos/rooms/<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.AlterField(
            model_name='room',
            name='picture2',
            field=models.ImageField(blank=True, default='', max_length=2000, upload_to='photos/rooms/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
