# Generated by Django 4.0.2 on 2022-04-30 08:54

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_alter_post_creator_alter_room_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='', max_length=2000, upload_to=rooms.models.post_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture2',
            field=models.ImageField(blank=True, default='', max_length=2000, upload_to=rooms.models.post_directory_path),
        ),
        migrations.AlterField(
            model_name='room',
            name='picture',
            field=models.ImageField(blank=True, default='', max_length=2000, upload_to=rooms.models.room_directory_path),
        ),
        migrations.AlterField(
            model_name='room',
            name='picture2',
            field=models.ImageField(blank=True, default='', max_length=2000, upload_to=rooms.models.room_directory_path),
        ),
    ]
