# Generated by Django 4.0.2 on 2022-05-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_post_picture_alter_post_picture2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-id']},
        ),
    ]
