# Generated by Django 4.0.2 on 2022-05-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='post',
        ),
    ]
