# Generated by Django 4.0.2 on 2022-06-22 13:34

import collectionsNft.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='Atest', max_length=200, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('nfts_array', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('picture', models.ImageField(blank=True, default='', max_length=1000, upload_to=collectionsNft.models.collection_directory_path)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='profiles.profile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
