# Generated by Django 4.0.2 on 2022-06-22 14:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('sale_type', models.CharField(choices=[('Auction', 'Auction'), ('Fixed price', 'Fixed')], default='Fixed price', max_length=50)),
                ('blockchain', models.CharField(choices=[('Ethereum', 'Ethereum'), ('Polygon', 'Polygon'), ('Other', 'Other')], default='Polygon', max_length=50)),
                ('price', models.IntegerField(default=1)),
                ('rarity', models.IntegerField(default=1)),
                ('royalties', models.IntegerField(default=0)),
                ('tokenId', models.IntegerField(unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='profiles.profile')),
            ],
        ),
    ]
