# Generated by Django 4.0.2 on 2022-02-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ordinal',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
