# Generated by Django 4.0.2 on 2022-06-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='creator',
        ),
    ]
