# Generated by Django 4.0.2 on 2022-06-22 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('nfts', '0002_remove_nft_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='profiles.profile'),
        ),
    ]
