# Generated by Django 4.0.2 on 2022-03-16 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0005_category_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
