# Generated by Django 4.0.2 on 2022-04-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0006_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='photo_main',
        ),
        migrations.AlterField(
            model_name='nft',
            name='blockchain',
            field=models.CharField(choices=[('Ethereum', 'Ethereum'), ('Polygon', 'Polygon'), ('Other', 'Other')], default='Polygon', max_length=50),
        ),
        migrations.AlterField(
            model_name='nft',
            name='creator',
            field=models.CharField(default='Artiste Anonyme', max_length=500),
        ),
    ]
