# Generated by Django 4.0.2 on 2022-04-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0019_alter_collection_picture_alter_creator_discordurl_and_more'),
        ('nfts', '0007_remove_nft_photo_main_alter_nft_blockchain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='tokenId',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='nft',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NFT', to='creators.creator'),
        ),
    ]
