# Generated by Django 4.0.2 on 2022-04-29 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0020_alter_creator_options_creator_user_and_more'),
        ('nfts', '0008_nft_tokenid_alter_nft_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='creators.creator'),
        ),
    ]
