# Generated by Django 4.0.2 on 2022-05-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0009_alter_nft_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='tokenId',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
