# Generated by Django 4.0.2 on 2022-05-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0010_alter_nft_tokenid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='tokenId',
            field=models.IntegerField(unique=True),
        ),
    ]
