# Generated by Django 4.0.2 on 2022-05-02 07:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0011_alter_nft_tokenid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
