# Generated by Django 4.0.2 on 2022-05-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0013_nft_royalties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='slug',
        ),
    ]
